export type Map009Memory = { state: "safe-zone" | "exploring" | "toxic-downpour" | "elite-active" | "boss-telegraph" | "boss-active" | "defeated"; eliteRevealed: boolean; telegraphStartedAt?: number };
export type Map009Input = { x: number; z: number; health: number; harvestedBlooms: number; defeatedStalkers: number; interacted: boolean; now: number };
export const MAP009_CANOPY_HAVEN = { x: 14, z: -8, radius: 7 }; export const MAP009_HIVE_ROOT = { x: 32, z: 28, radius: 8 }; const period = 300000, duration = 75000, offset = 205000;
export const initialMap009Encounter = (): Map009Memory => ({ state: "safe-zone", eliteRevealed: false });
export function resolveMap009Encounter(memory: Map009Memory, input: Map009Input) { const downpour = ((Math.max(0, input.now) + offset) % period) < duration; const sheltered = Math.hypot(input.x - MAP009_CANOPY_HAVEN.x, input.z - MAP009_CANOPY_HAVEN.z) <= MAP009_CANOPY_HAVEN.radius; const common = { downpourActive: downpour, sheltered, toxinDamagePerSecond: downpour && !sheltered ? 5 : 0, canopyProtectionActive: sheltered };
 if (input.health <= 0) return { memory: { ...memory, state: "defeated" as const }, event: "safe-reset" as const, spawnStalkers: 0, activateElite: false, activateBoss: false, warning: "TOXIC DOWNPOUR CRITICAL · returning to Botanist Iris", ...common };
 if (memory.state === "boss-telegraph" && memory.telegraphStartedAt && input.now-memory.telegraphStartedAt>=2600) return { memory:{...memory,state:"boss-active" as const},event:"verdant-hive-mind" as const,spawnStalkers:0,activateElite:memory.eliteRevealed,activateBoss:true,warning:"VERDANT HIVE MIND AWAKENED",...common };
 if (memory.state === "boss-active") return { memory,event:"none" as const,spawnStalkers:0,activateElite:memory.eliteRevealed,activateBoss:true,warning:"VERDANT HIVE MIND ENGAGED · follow canopy cover",...common };
 if(memory.eliteRevealed&&!downpour&&input.interacted&&Math.hypot(input.x-MAP009_HIVE_ROOT.x,input.z-MAP009_HIVE_ROOT.z)<=MAP009_HIVE_ROOT.radius)return{memory:{...memory,state:"boss-telegraph" as const,telegraphStartedAt:input.now},event:"verdant-hive-mind" as const,spawnStalkers:0,activateElite:true,activateBoss:false,warning:"HIVE ROOT DISTURBED · HOLD POSITION",...common};
 const elite=input.harvestedBlooms>=3||input.defeatedStalkers>=4;if(!memory.eliteRevealed&&elite)return{memory:{...memory,state:"elite-active" as const,eliteRevealed:true},event:"elite-revealed" as const,spawnStalkers:0,activateElite:true,activateBoss:false,warning:"THORNBACK BEHEMOTH EMERGES",...common};const state: Map009Memory["state"]=sheltered?"safe-zone":downpour?"toxic-downpour":memory.eliteRevealed?"elite-active":"exploring";return{memory:{...memory,state},event:memory.state!=="toxic-downpour"&&state==="toxic-downpour"?"toxic-downpour" as const:"none" as const,spawnStalkers:memory.state!=="toxic-downpour"&&state==="toxic-downpour"?2:0,activateElite:memory.eliteRevealed,activateBoss:false,warning:downpour?(sheltered?"TOXIC DOWNPOUR · canopy protection active":"TOXIC DOWNPOUR ACTIVE · reach Canopy Haven"):undefined,...common};
}
