export type Map007Input = { x: number; z: number; health: number; harvestedCrystals: number; defeatedWeavers: number; interacted: boolean; now: number };
export type Map007Memory = { state: "safe-zone" | "exploring" | "blizzard" | "elite-active" | "boss-telegraph" | "boss-active" | "defeated"; eliteRevealed: boolean; telegraphStartedAt?: number };
export type Map007Result = { memory: Map007Memory; event: "none" | "blizzard" | "elite-revealed" | "glacial-terror" | "safe-reset"; blizzardActive: boolean; sheltered: boolean; frostbiteOverlay: boolean; coldDamagePerSecond: number; spawnWeavers: number; activateElite: boolean; activateBoss: boolean; warning?: string };
export const MAP007_STEAM_VENT = { x: 14, z: -8, radius: 7 }; export const MAP007_TERROR_RIFT = { x: 32, z: 28, radius: 8 }; export const MAP007_BLIZZARD_PERIOD_MS = 300_000; export const MAP007_BLIZZARD_DURATION_MS = 80_000; export const MAP007_BLIZZARD_OFFSET_MS = 140_000; export const MAP007_TELEGRAPH_MS = 2600;
const distance = (x: number, z: number, point: { x: number; z: number }) => Math.hypot(x - point.x, z - point.z); const blizzardWindow = (now: number) => ((Math.max(0, now) + MAP007_BLIZZARD_OFFSET_MS) % MAP007_BLIZZARD_PERIOD_MS) < MAP007_BLIZZARD_DURATION_MS;
export const initialMap007Encounter = (): Map007Memory => ({ state: "safe-zone", eliteRevealed: false });
export function resolveMap007Encounter(memory: Map007Memory, input: Map007Input): Map007Result { const blizzardActive = blizzardWindow(input.now); const sheltered = distance(input.x, input.z, MAP007_STEAM_VENT) <= MAP007_STEAM_VENT.radius; const common = { blizzardActive, sheltered, frostbiteOverlay: blizzardActive && !sheltered, coldDamagePerSecond: blizzardActive && !sheltered ? 5 : 0 };
  if (input.health <= 0) return { memory: { ...memory, state: "defeated" }, event: "safe-reset", spawnWeavers: 0, activateElite: false, activateBoss: false, warning: "FROSTBITE CRITICAL · returning to Scout Frost", ...common };
  if (memory.state === "boss-telegraph" && memory.telegraphStartedAt && input.now - memory.telegraphStartedAt >= MAP007_TELEGRAPH_MS) return { memory: { ...memory, state: "boss-active" }, event: "glacial-terror", spawnWeavers: 0, activateElite: memory.eliteRevealed, activateBoss: true, warning: "GLACIAL TERROR HAS AWAKENED", ...common };
  if (memory.state === "boss-active") return { memory, event: "none", spawnWeavers: 0, activateElite: memory.eliteRevealed, activateBoss: true, warning: "GLACIAL TERROR ENGAGED · follow the steam vents", ...common };
  if (memory.eliteRevealed && !blizzardActive && input.interacted && distance(input.x, input.z, MAP007_TERROR_RIFT) <= MAP007_TERROR_RIFT.radius) return { memory: { ...memory, state: "boss-telegraph", telegraphStartedAt: input.now }, event: "glacial-terror", spawnWeavers: 0, activateElite: true, activateBoss: false, warning: "FROZEN RIFT DISTURBED · HOLD POSITION", ...common };
  const eliteCondition = input.harvestedCrystals >= 3 || input.defeatedWeavers >= 4; if (!memory.eliteRevealed && eliteCondition) return { memory: { ...memory, state: "elite-active", eliteRevealed: true }, event: "elite-revealed", spawnWeavers: 0, activateElite: true, activateBoss: false, warning: "CRYO-BEAST AMBUSH · thermal trail lost", ...common };
  const state: Map007Memory["state"] = sheltered ? "safe-zone" : blizzardActive ? "blizzard" : memory.eliteRevealed ? "elite-active" : "exploring"; const started = state === "blizzard" && memory.state !== "blizzard"; return { memory: { ...memory, state }, event: started ? "blizzard" : "none", spawnWeavers: started ? 2 : 0, activateElite: memory.eliteRevealed, activateBoss: false, warning: blizzardActive ? (sheltered ? "BLIZZARD · steam vent shelter holding" : "BLIZZARD ACTIVE · find Scout Frost steam vent") : undefined, ...common };
}
