export type Map008Memory = { state: "safe-zone" | "exploring" | "defense-sweep" | "elite-active" | "boss-telegraph" | "boss-active" | "defeated"; eliteRevealed: boolean; telegraphStartedAt?: number };
export type Map008Input = { x: number; z: number; health: number; harvestedRelics: number; defeatedDrones: number; interacted: boolean; now: number };
export const MAP008_RUNE_TERMINAL = { x: 14, z: -8, radius: 7 }; export const MAP008_MATRIX_CORE = { x: 32, z: 28, radius: 8 }; const period = 300000, duration = 75000, offset = 180000;
export const initialMap008Encounter = (): Map008Memory => ({ state: "safe-zone", eliteRevealed: false });
export function resolveMap008Encounter(memory: Map008Memory, input: Map008Input) { const sweep = ((Math.max(0, input.now) + offset) % period) < duration; const sheltered = Math.hypot(input.x - MAP008_RUNE_TERMINAL.x, input.z - MAP008_RUNE_TERMINAL.z) <= MAP008_RUNE_TERMINAL.radius; const common = { sweepActive: sweep, sheltered, laserDamagePerSecond: sweep && !sheltered ? 5 : 0, temporaryShieldActive: sheltered };
 if (input.health <= 0) return { memory: { ...memory, state: "defeated" as const }, event: "safe-reset" as const, spawnDrones: 0, activateElite: false, activateBoss: false, warning: "DEFENSE SWEEP CRITICAL · returning to Historian Kael", ...common };
 if (memory.state === "boss-telegraph" && memory.telegraphStartedAt && input.now-memory.telegraphStartedAt>=2600) return { memory:{...memory,state:"boss-active" as const},event:"matrix-overlord" as const,spawnDrones:0,activateElite:memory.eliteRevealed,activateBoss:true,warning:"MATRIX OVERLORD ONLINE",...common };
 if (memory.state === "boss-active") return { memory,event:"none" as const,spawnDrones:0,activateElite:memory.eliteRevealed,activateBoss:true,warning:"MATRIX OVERLORD ENGAGED · follow rune pulses",...common };
 if(memory.eliteRevealed&&!sweep&&input.interacted&&Math.hypot(input.x-MAP008_MATRIX_CORE.x,input.z-MAP008_MATRIX_CORE.z)<=MAP008_MATRIX_CORE.radius)return{memory:{...memory,state:"boss-telegraph" as const,telegraphStartedAt:input.now},event:"matrix-overlord" as const,spawnDrones:0,activateElite:true,activateBoss:false,warning:"MATRIX CORE DISTURBED · HOLD POSITION",...common};
 const elite=input.harvestedRelics>=3||input.defeatedDrones>=4;if(!memory.eliteRevealed&&elite)return{memory:{...memory,state:"elite-active" as const,eliteRevealed:true},event:"elite-revealed" as const,spawnDrones:0,activateElite:true,activateBoss:false,warning:"RUIN GUARDIAN ACTIVATED",...common};const state: Map008Memory["state"]=sheltered?"safe-zone":sweep?"defense-sweep":memory.eliteRevealed?"elite-active":"exploring";return{memory:{...memory,state},event:memory.state!=="defense-sweep"&&state==="defense-sweep"?"defense-sweep" as const:"none" as const,spawnDrones:memory.state!=="defense-sweep"&&state==="defense-sweep"?2:0,activateElite:memory.eliteRevealed,activateBoss:false,warning:sweep?(sheltered?"DEFENSE SWEEP · rune shield active":"DEFENSE SWEEP ACTIVE · reach Rune Terminal"):undefined,...common};
}
