export type Map010Memory = { state: "idle" | "pulse-warning" | "pulse-active" | "cooldown" | "elite-active" | "boss-telegraph" | "boss-active" | "defeated"; eliteRevealed: boolean; telegraphStartedAt?: number };
export type Map010Input = { x: number; z: number; health: number; harvestedEssence: number; defeatedLarvae: number; interacted: boolean; now: number; menuOpen?: boolean };
export const MAP010_STABLE_PYLON = { x: 12, z: -12, radius: 7 }; export const MAP010_SINGULARITY_GATE = { x: 31, z: 27, radius: 8 }; const period = 60000, warningDuration = 4500, pulseDuration = 5000;
export const initialMap010Encounter = (): Map010Memory => ({ state: "idle", eliteRevealed: false });
export function resolveMap010Encounter(memory: Map010Memory, input: Map010Input) { const clock = Math.max(0, input.now) % period; const warning = clock >= period - warningDuration; const active = clock < pulseDuration; const protectedByPylon = Math.hypot(input.x - MAP010_STABLE_PYLON.x, input.z - MAP010_STABLE_PYLON.z) <= MAP010_STABLE_PYLON.radius; const common = { pulseActive: active, protectedByPylon, voidDamagePerSecond: active && !protectedByPylon && !input.menuOpen ? 6 : 0, pulseTimerMs: active ? pulseDuration - clock : warning ? period - clock : period - clock, inventoryMutation: false as const };
 if (input.health <= 0) return { memory:{...memory,state:"defeated" as const},event:"safe-reset" as const,activateElite:false,activateBoss:false,warning:"VOID DECAY CRITICAL · returning to Stable Rift Pylon",...common };
 if(memory.state==="boss-telegraph"&&memory.telegraphStartedAt&&input.now-memory.telegraphStartedAt>=2600)return{memory:{...memory,state:"boss-active" as const},event:"void-singularity" as const,activateElite:memory.eliteRevealed,activateBoss:true,warning:"VOID SINGULARITY UNSEALED",...common};
 if(memory.state==="boss-active")return{memory,event:"none" as const,activateElite:memory.eliteRevealed,activateBoss:true,warning:"VOID SINGULARITY ENGAGED · USE PYLON SHIELDING",...common};
 const atGate=Math.hypot(input.x-MAP010_SINGULARITY_GATE.x,input.z-MAP010_SINGULARITY_GATE.z)<=MAP010_SINGULARITY_GATE.radius;if(memory.eliteRevealed&&input.harvestedEssence>=10&&!active&&input.interacted&&atGate)return{memory:{...memory,state:"boss-telegraph" as const,telegraphStartedAt:input.now},event:"void-singularity" as const,activateElite:true,activateBoss:false,warning:"10 VOID ESSENCE RESONATE · SINGULARITY OPENING",...common};
 const elite=input.harvestedEssence>=5||input.defeatedLarvae>=4;if(!memory.eliteRevealed&&elite)return{memory:{...memory,state:"elite-active" as const,eliteRevealed:true},event:"elite-revealed" as const,activateElite:true,activateBoss:false,warning:"RIFT HORROR DETECTED",...common};
 const state:Map010Memory["state"]=active?"pulse-active":warning?"pulse-warning":clock<pulseDuration+6000?"cooldown":memory.eliteRevealed?"elite-active":"idle";return{memory:{...memory,state},event:memory.state!=="pulse-warning"&&state==="pulse-warning"?"pulse-warning" as const:memory.state!=="pulse-active"&&state==="pulse-active"?"void-pulse" as const:"none" as const,activateElite:memory.eliteRevealed,activateBoss:false,warning:active?(protectedByPylon?"VOID PULSE · pylon shielding stable":"VOID PULSE ACTIVE · reach Stable Rift Pylon"):warning?"VOID PULSE INCOMING · 4.5s":"",...common};
}
